import React from "react";
import type { RiskLevel } from "../../../lib/privacyRisk";
import type { DecisionApprovalStatus } from "../../../lib/residualDecision";

export const cardStyle = { background: "white", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "28px", marginBottom: "20px" };
export const headingStyle = { color: "#0f172a", marginTop: 0, marginBottom: "18px" };
export const selectStyle = { width: "100%", padding: "13px 14px", borderRadius: "8px", border: "1px solid #cbd5e1", background: "white", fontSize: "16px", color: "#0f172a" };
export const noticeStyle = { color: "#64748b", lineHeight: 1.6 };
export const secondaryButtonStyle = { padding: "12px 18px", borderRadius: "8px", border: "none", background: "#0f172a", color: "white", fontWeight: 600, cursor: "pointer" };
export const removeButtonStyle = { border: "none", background: "transparent", color: "#64748b", cursor: "pointer", fontSize: "13px" };
export function StepNumber({ number }: { number: string }) { return <div style={{ width: "34px", height: "34px", borderRadius: "50%", background: "#1d4ed8", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, marginBottom: "16px" }}>{number}</div>; }
export function SelectionSummary({ count, label }: { count: number; label: string }) { return <div style={{ marginTop: "24px", padding: "16px", background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: "10px", color: "#166534" }}><strong>{count} {label}{count !== 1 ? "s" : ""} selected</strong></div>; }
export function riskColor(level: RiskLevel): string { switch (level) { case "Critical": return "#991b1b"; case "High": return "#dc2626"; case "Medium": return "#d97706"; case "Low": return "#15803d"; default: return "#475569"; } }
export function riskBackground(level: RiskLevel): string { switch (level) { case "Critical": return "#fee2e2"; case "High": return "#fef2f2"; case "Medium": return "#fffbeb"; case "Low": return "#f0fdf4"; default: return "#f8fafc"; } }
export function approvalColor(status: DecisionApprovalStatus): string { switch (status) { case "Pending": return "#b45309"; case "Approved": return "#15803d"; case "Rejected": return "#b91c1c"; default: return "#475569"; } }
export function approvalBackground(status: DecisionApprovalStatus): string { switch (status) { case "Pending": return "#fffbeb"; case "Approved": return "#f0fdf4"; case "Rejected": return "#fee2e2"; default: return "#f8fafc"; } }
export function treatmentStatusColor(status: string): string { switch (status) { case "Completed": case "Accepted": return "#15803d"; case "In Progress": return "#2563eb"; case "Open": return "#b45309"; default: return "#475569"; } }
export function treatmentStatusBackground(status: string): string { switch (status) { case "Completed": case "Accepted": return "#f0fdf4"; case "In Progress": return "#eff6ff"; case "Open": return "#fffbeb"; default: return "#f8fafc"; } }
export function GovernanceSummaryCard({label,value,level}:{label:string;value:number;level?:RiskLevel}) { return <div style={{padding:"16px",borderRadius:"10px",background:level?riskBackground(level):"#f8fafc",border:"1px solid #e2e8f0"}}><div style={{fontSize:"11px",fontWeight:700,color:"#64748b",letterSpacing:"1px"}}>{label}</div><div style={{marginTop:"5px",fontSize:"26px",fontWeight:800,color:level?riskColor(level):"#0f172a"}}>{value}</div></div>; }
export function GovernanceField({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}) { return <div><label style={{display:"block",fontWeight:700,color:"#0f172a",marginBottom:"8px",fontSize:"13px"}}>{label}</label><input type={type} value={value} onChange={e=>onChange(e.target.value)} style={{width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #cbd5e1",borderRadius:"8px",background:"white",color:"#0f172a",fontSize:"14px"}} /></div>; }
export function ResidualSummaryCard({label,value,level}:{label:string;value:number;level?:RiskLevel}) { return <div style={{padding:"18px",borderRadius:"10px",background:level?riskBackground(level):"#f8fafc",border:"1px solid #e2e8f0"}}><div style={{fontSize:"11px",fontWeight:700,color:"#64748b",letterSpacing:"1px"}}>{label}</div><div style={{marginTop:"6px",fontSize:"28px",fontWeight:800,color:level?riskColor(level):"#0f172a"}}>{value}</div></div>; }
export function DecisionSummaryCard({label,value,level}:{label:string;value:number;level?:RiskLevel}) { return <div style={{padding:"18px",borderRadius:"10px",background:level?riskBackground(level):"#f8fafc",border:"1px solid #e2e8f0"}}><div style={{fontSize:"11px",fontWeight:700,color:"#64748b",letterSpacing:"1px"}}>{label}</div><div style={{marginTop:"6px",fontSize:"28px",fontWeight:800,color:level?riskColor(level):"#0f172a"}}>{value}</div></div>; }
export function ResidualMeta({label,value,level}:{label:string;value:string;level?:RiskLevel}) { return <div style={{padding:"12px",background:"#f8fafc",borderRadius:"8px"}}><div style={{fontSize:"11px",fontWeight:700,color:"#64748b",textTransform:"uppercase",marginBottom:"5px"}}>{label}</div><div style={{fontSize:"14px",fontWeight:level?700:500,color:level?riskColor(level):"#334155",lineHeight:1.5}}>{value}</div></div>; }
