"use client";
import type { AssessmentProfile } from "../types";
import type { RiskTreatmentAction, TreatmentStatus } from "../../../lib/riskTreatment";
import { treatmentStatusBackground, treatmentStatusColor, riskBackground, riskColor } from "./shared";

export default function Step12RemediationTracker({assessmentProfile,actions,onStatusChange}:{assessmentProfile:AssessmentProfile;actions:RiskTreatmentAction[];onStatusChange:(id:string,status:TreatmentStatus)=>void}) {
  const open=actions.filter(a=>a.status==="Open").length, progress=actions.filter(a=>a.status==="In Progress").length, closed=actions.filter(a=>a.status==="Completed"||a.status==="Accepted").length;
  return <section style={{marginTop:24,marginBottom:24}}><div style={card}><div style={kicker}>STEP 12</div><h2 style={h2}>Remediation Tracker</h2><p style={p}>Track treatment progress from the same parent-owned state used by Steps 8–11.</p><div style={profile}>{assessmentProfile.organisationName} • {assessmentProfile.assessmentName} • {assessmentProfile.assessmentId}</div><div style={grid}><S label="OPEN" value={open}/><S label="IN PROGRESS" value={progress}/><S label="CLOSED" value={closed}/></div></div><div style={card}>{actions.length===0?<Empty/>:actions.map(a=><div key={a.id} style={{border:"1px solid #e2e8f0",borderRadius:12,padding:20,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",gap:15,flexWrap:"wrap"}}><div><div style={small}>{a.category}</div><h3 style={{margin:"6px 0",color:"#0f172a"}}>{a.riskTitle}</h3><p style={{margin:0,color:"#475569",lineHeight:1.6}}>{a.recommendedTreatment}</p></div><span style={badge(a.status)}>{a.status}</span></div><div style={grid4}><M label="Priority" value={a.priority}/><M label="Owner" value={a.owner}/><M label="Timeframe" value={a.timeframe}/><M label="Effort" value={a.effort}/></div><div style={{marginTop:14,maxWidth:320}}><label style={label}>Treatment status</label><select value={a.status} onChange={e=>onStatusChange(a.id,e.target.value as TreatmentStatus)} style={input}><option>Open</option><option>In Progress</option><option>Completed</option><option>Accepted</option></select></div></div>)}</div></section>;
}
const card={background:"white",border:"1px solid #e2e8f0",borderRadius:14,padding:28,marginBottom:20}; const h2={marginTop:0,color:"#0f172a"}; const p={color:"#64748b",lineHeight:1.6,maxWidth:760}; const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:20}; const grid4={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:16}; const profile={marginTop:18,padding:"14px 16px",background:"#f8fafc",border:"1px solid #e2e8f0",borderRadius:10,color:"#475569",fontSize:13}; const small={fontSize:11,fontWeight:700,color:"#64748b",letterSpacing:1}; const label={display:"block",fontWeight:700,color:"#0f172a",marginBottom:7,fontSize:13}; const input={width:"100%",boxSizing:"border-box" as const,padding:"11px 12px",border:"1px solid #cbd5e1",borderRadius:8,background:"white",color:"#0f172a",fontSize:14}; function badge(s:string){const x=s==="Completed"?{b:"#f0fdf4",c:"#15803d"}:s==="Accepted"?{b:"#eff6ff",c:"#1d4ed8"}:s==="In Progress"?{b:"#fffbeb",c:"#b45309"}:{b:"#f8fafc",c:"#475569"};return {padding:"6px 10px",borderRadius:20,background:x.b,color:x.c,fontWeight:700,fontSize:12,height:"fit-content"}} function S({label,value}:{label:string;value:number}){return <div style={{padding:18,borderRadius:10,background:"#f8fafc",border:"1px solid #e2e8f0"}}><div style={{fontSize:11,fontWeight:700,color:"#64748b",letterSpacing:1}}>{label}</div><div style={{marginTop:6,fontSize:28,fontWeight:800,color:"#0f172a"}}>{value}</div></div>} function M({label,value}:{label:string;value:string}){return <div style={{padding:12,background:"#f8fafc",borderRadius:8}}><div style={{fontSize:11,fontWeight:700,color:"#64748b",textTransform:"uppercase",marginBottom:5}}>{label}</div><div style={{fontSize:13,color:"#334155"}}>{value}</div></div>} function Empty(){return <div style={{padding:18,background:"#f8fafc",borderRadius:10,color:"#64748b"}}>No remediation actions are currently available.</div>}
